export const SET_REGISTER_USER = 'SET_REGISTER_USER';
export const SET_VALID_REGISTER = 'SET_VALID_REGISTER';
export const SET_VALID_LOGIN = 'SET_VALID_LOGIN';
export const ADD_PRODUCT = 'ADD_PRODUCT';